name: Lint
on:
 - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Lint
        run: yarn && yarn lint
